package org.someth2say.taijitu.cli;

import org.apache.commons.configuration2.ImmutableHierarchicalConfiguration;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.someth2say.taijitu.cli.config.impl.TaijituCfg;
import org.someth2say.taijitu.cli.config.interfaces.IComparisonCfg;
import org.someth2say.taijitu.cli.config.interfaces.ITaijituCfg;
import org.someth2say.taijitu.cli.registry.MapperRegistry;
import org.someth2say.taijitu.cli.registry.SourceRegistry;
import org.someth2say.taijitu.cli.registry.ValueEqualityRegistry;
import org.someth2say.taijitu.cli.source.query.ConnectionManager;
import org.someth2say.taijitu.cli.util.FileUtil;
import org.someth2say.taijitu.compare.result.Difference;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.*;
import java.util.stream.Stream;

import static org.someth2say.taijitu.cli.config.DefaultConfig.DEFAULT_CONFIG_FILE;

/**
 * @author Jordi Sola
 */
public final class TaijituCli {

    private static final Logger logger = LoggerFactory.getLogger(TaijituCli.class);

    private static ITaijituCfg configFromApache(final ImmutableHierarchicalConfiguration properties) {
        return TaijituCfg.fromApacheConfig(properties);
    }


    private static ITaijituCfg configFromFile(final String fileName) throws TaijituCliException {
        return TaijituCfg.fromFile(fileName);
    }

    private static void performSetup(final ITaijituCfg config) throws TaijituCliException {
        try {
            setupRegistries(config);
        } catch (Exception e) {
            throw new TaijituCliException("Unable to prepare TaijituCli.", e);
        }
    }

    //This registry stuff may be moved to a IC context (Weld?)
    private static void setupRegistries(final ITaijituCfg config) {
        if (config.isUseScanClassPath()) {
            ValueEqualityRegistry.scanClassPath();
            SourceRegistry.scanClassPath();
            MapperRegistry.scanClassPath();
        } else {
            ValueEqualityRegistry.useDefaults();
            SourceRegistry.useDefaults();
            MapperRegistry.useDefaults();
        }
    }

    public static void main(final String[] args) {
        if (args.length != 1) {
            FileUtil.dumpResource("usage-taijitu.txt");
        } else {
            // run comparison with default values
            try {
                TaijituCli.compare(args[0]);
            } catch (TaijituCliException e) {
                logger.error("Unable to start: ", e);
            }
        }
    }

    public static List<Stream<Difference<?>>> compare() throws TaijituCliException {
        return compare(DEFAULT_CONFIG_FILE);
    }

    private static List<Stream<Difference<?>>> compare(final String fileName) throws TaijituCliException {
        return compare(configFromFile(fileName));
    }


    public static List<Stream<Difference<?>>> compare(final ImmutableHierarchicalConfiguration properties) throws TaijituCliException {
        return compare(configFromApache(properties));
    }


    public static List<Stream<Difference<?>>> compare(final ITaijituCfg config) throws TaijituCliException {
        logger.info("Start comparisons.");
        performSetup(config);

        List<IComparisonCfg> comparisons = config.getComparisons();

        final CompletionService<Stream<Difference<?>>> completionService = runComparisons(config);

        // Collect results
        final List<Stream<Difference<?>>> result = getComparisonResults(completionService, comparisons);

        // Close all open connections generated by comparison queries:
        closeDataSources();

        return result;

    }

    private static CompletionService<Stream<Difference<?>>> runComparisons(final ITaijituCfg config) {
        final ExecutorService executorService = Executors.newFixedThreadPool(config.getThreads());
        CompletionService<Stream<Difference<?>>> completionService = new ExecutorCompletionService<>(executorService);

        config.getComparisons().forEach(comparison -> completionService.submit(new TaijituCliRunner(comparison)));

        executorService.shutdown();

        return completionService;
    }



    private static List<Stream<Difference<?>>> getComparisonResults(CompletionService<Stream<Difference<?>>> completionService,
                                                                    List<IComparisonCfg> iComparisonCfgs) {
        final List<Stream<Difference<?>>> result = new ArrayList<>(iComparisonCfgs.size());

        for (int i = 0; i < iComparisonCfgs.size(); i++) {
            try {
                Future<Stream<Difference<?>>> future = completionService.take();
                try {
                    result.add(future.get());
                } catch (ExecutionException e) {
                    logger.error("Unable to obtain comparison result.", e);
                    result.add(null);
                }
            } catch (InterruptedException e) {
                logger.error("Unable to obtain comparison result.", e);
                result.add(null);
            }
        }
        return result;
    }

    private static void closeDataSources() {
        ConnectionManager.closeAllDataSources();
    }

}
